---
title: "cartograph_notes"
author: "Aleksander Wael"
date: "4/24/2023"
output: html_document
---

```{r}
# Load libraries
'library(dplyr)        # data wrangling
library(cartogram)    # for the cartogram
library(ggplot2)      # to realize the plots
library(broom)        # from geospatial format to data frame
library(tweenr)       # to create transition dataframe between 2 states
library(gganimate)    # To realize the animation
library(maptools)     # world boundaries coordinates
library(viridis)      # for a nice color palette'

# !install.packages('rgeos', type='source')
# !install.packages('rgdal', type='source')

pacman::p_load(dplyr, plyr, cartogram, ggplot2, broom, tweenr, gganimate, maptools, viridis, stringi, sf, rgeos, rgdal, mapproj)
```

```{r}
# Get the shape file of Africa
data(wrld_simpl)
afr=wrld_simpl[wrld_simpl$REGION==2,]

# A basic representation
wrld_simpl@data
```

```{r}
# Prepare municipalities
library(raster)
municipalities <- getData("GADM", country = "DK", level = 2)
```

```{r}
indbygger_data = read.csv2("data/indbygger_data.csv", header = T)
indbygger_data <- na.omit(indbygger_data)

areal_data = read.csv2("data/areal_data.csv", header = T)
```

```{r}
# Changing kommune names for indbygger_data df

indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "", regex = " Kommune") # Københavns, Vesthimmerlands, Bornholms, AArhus
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "København", regex = "Københavns")
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "Vesthimmerland", regex = "Vesthimmerlands")
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "Bornholm", regex = "Bornholms")
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "Århus", regex = "Aarhus")
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "", regex = "\\(.*\\)")
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "", regex = " ")
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "Høje Taastrup", regex = "Høje-Taastrup")
indbygger_data <- add_row(indbygger_data, Kommune = "Christiansø")
```

```{r}
# Joining DF
# Make into spatial object again
colnames(municipalities@data)[7] <- "Kommune"
municipalities@data <- join(municipalities@data, indbygger_data, by = "Kommune")
```

```{r}
mun_sf <- st_as_sf(municipalities)
mun_sf <- st_transform(mun_sf, crs = 25832)

mun_sf$X1993 <- as.numeric(mun_sf$X1993)
mun_sf$X1994 <- as.numeric(mun_sf$X1994)
mun_sf$X1995 <- as.numeric(mun_sf$X1995)
mun_sf$X1996 <- as.numeric(mun_sf$X1996)
mun_sf$X1997 <- as.numeric(mun_sf$X1997)
mun_sf$X1998 <- as.numeric(mun_sf$X1998)
mun_sf$X1999 <- as.numeric(mun_sf$X1999)
mun_sf$X2000 <- as.numeric(mun_sf$X2000)
mun_sf$X2001 <- as.numeric(mun_sf$X2001)

municipalities_projected <- as_Spatial(mun_sf)
```

```{r}
dk_cartogram <- cartogram_cont(mun_sf, "X1993", iter = 7)

dk_cartogram_spdf <- as_Spatial(dk_cartogram)
```

```{r}
mun_df <- tidy(municipalities_projected, region = "Kommune") %>% 
  left_join(., municipalities_projected@data, by=c("id"="Kommune"))

cartogram_df <- tidy(dk_cartogram_sf, region = "Kommune") %>% 
  left_join(., municipalities_projected@data, by=c("id"="Kommune"))

afr_df <- tidy(afr) %>% 
  left_join(., afr@data, by=c("id"="ISO3"))
```

```{r}
# Centers for kommune labels
# Calculate the position of state labels
centers <- cbind.data.frame(data.frame(gCentroid(municipalities_projected, byid=TRUE), id=municipalities_projected$Kommune))
centers_cartogram <- cbind.data.frame(data.frame(gCentroid(dk_cartogram_spdf, byid=TRUE), id=dk_cartogram_spdf$Kommune))
```

```{r}
ggplot() +
  geom_sf(data = dk_cartogram, aes(fill = X1993), size=0, alpha=0.9)+
  theme_void()+
  scale_fill_viridis(name="Population (M)", breaks=c(1,50,100, 140), guide = guide_legend( keyheight = unit(3, units = "mm"), keywidth=unit(12, units = "mm"), label.position = "bottom", title.position = 'top', nrow=1)) +
  labs(title = "Denmark", subtitle="Population per kommune in 1993" ) +
  geom_text(data=centers_cartogram, aes(x=x, y=y, label=id), color="white", size=3, alpha=0.6) +
  theme(
    text = element_text(color = "#22211d"), 
    plot.background = element_rect(fill = "#f5f5f4", color = NA), 
    panel.background = element_rect(fill = "#f5f5f4", color = NA), 
    legend.background = element_rect(fill = "#f5f5f4", color = NA),
    plot.title = element_text(size= 22, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
    plot.subtitle = element_text(size= 13, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
    legend.position = c(0.8, 0.8)
  )
```












